[build]
  command = "npm run build"
  publish = "dist"

# Optional: cache node_modules between builds for faster deploys
[build.environment]
  NPM_FLAGS = "--no-fund --no-audit"

# Redirect all routes to index.html for SPA routing (React + Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
